# repos:

#   - repo: https://github.com/psf/black
#     rev: 23.1.0
#     hooks:
#       - id: black
#         language_version: python3

#   - repo: https://github.com/PyCQA/flake8
#     rev: 6.0.0
#     hooks:
#       - id: flake8
#         args: ["--max-line-length=88"]

#   - repo: https://github.com/pre-commit/mirrors-eslint
#     rev: v8.23.0
#     hooks:
#       - id: eslint

#   - repo: https://github.com/pre-commit/mirrors-prettier
#     rev: v2.7.1
#     hooks:
#       - id: prettier

#   - repo: https://github.com/pytest-dev/pytest
#     rev: 7.1.2
#     hooks:
#       - id: pytest

#   - repo: https://github.com/espressif/conventional-precommit-linter
#     rev: v1.10.0
#     hooks:
#       - id: conventional-precommit-linter
#         stages: [commit-msg]


repos:
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.23.0
  #   hooks:
  #     - id: eslint
  #       args: ["--fix"]


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        # Match files for formatting
        files: \.(js|json|css|md)$
