# repos:

#   - repo: https://github.com/psf/black
#     rev: 23.1.0
#     hooks:
#       - id: black
#         language_version: python3

#   - repo: https://github.com/PyCQA/flake8
#     rev: 6.0.0
#     hooks:
#       - id: flake8
#         args: ["--max-line-length=88"]

#   - repo: https://github.com/pre-commit/mirrors-eslint
#     rev: v8.23.0
#     hooks:
#       - id: eslint

#   - repo: https://github.com/pre-commit/mirrors-prettier
#     rev: v2.7.1
#     hooks:
#       - id: prettier

#   - repo: https://github.com/pytest-dev/pytest
#     rev: 7.1.2
#     hooks:
#       - id: pytest

#   - repo: https://github.com/espressif/conventional-precommit-linter
#     rev: v1.10.0
#     hooks:
#       - id: conventional-precommit-linter
#         stages: [commit-msg]

# - repo: https://github.com/pre-commit/mirrors-eslint
#   rev: v8.23.0
#   hooks:
#     - id: eslint
#       args: ["--fix"]

# - repo: https://github.com/pre-commit/mirrors-prettier
#   rev: v2.7.1
#   hooks:
#     - id: prettier
#       # Match files for formatting
#       files: \.(js|json|css|md)$

# repos:
#   -   id: eslint
#     name: eslint
#     description: ''
#     entry: eslint
#     language: node
#     'types': [javascript]
#     args: []
#     require_serial: false
#     additional_dependencies: ["eslint@9.18.0"]
#     minimum_pre_commit_version: '0'

#   # Run Prettier for formatting
#   -   id: prettier
#     name: prettier
#     description: ''
#     entry: prettier --write --ignore-unknown
#     language: node
#     'types': [text]
#     args: []
#     require_serial: false
#     additional_dependencies: ["prettier@4.0.0-alpha.8"]
#     minimum_pre_commit_version: '0'

#   # Run tests before committing
#   - repo: local
#     hooks:
#       - id: run-tests
#         name: Run Tests
#         entry: npm test
#         language: system
#         pass_filenames: false
#         always_run: true

#   # - id: commitlint
#   name: commitlint
#   description: Commitlint hook
#   language: node
#   entry: commitlint --edit
#   pass_filenames: false
#   always_run: true
# - id: commitlint-travis
#   name: Check commit messages on Travis CI
#   description: Lint all relevant commits for a change or PR on Travis CI
#   language: node
#   entry: commitlint-travis
#   always_run: true
#   pass_filenames: false

# repos:
#   # Run ESLint for linting
#   - repo: https://github.com/pre-commit/mirrors-eslint
#     rev: v9.18.0 # Specify the version
#     hooks:
#       - id: eslint
#         name: eslint
#         description: Lint JavaScript files using ESLint
#         entry: eslint
#         language: node
#         types: [javascript]
#         args: []
#         require_serial: false
#         additional_dependencies: ["eslint@9.18.0"]
#         minimum_pre_commit_version: "2.20.0"

#   # Run Prettier for formatting
#   - repo: https://github.com/pre-commit/mirrors-prettier
#     rev: v4.0.0-alpha.8 # Specify the version
#     hooks:
#       - id: prettier
#         name: prettier
#         description: Format files using Prettier
#         entry: prettier --write --ignore-unknown
#         language: node
#         types: [text]
#         args: []
#         require_serial: false
#         additional_dependencies: ["prettier@4.0.0-alpha.8"]
#         minimum_pre_commit_version: "2.20.0"

#   # Run tests before committing
#   - repo: local
#     hooks:
#       - id: run-tests
#         name: Run Tests
#         description: Run all tests before committing
#         entry: npm test
#         language: system
#         pass_filenames: false
#         always_run: true

#   # Commitlint for commit message validation
#   - repo: local
#     hooks:
#       - id: commitlint
#         name: commitlint
#         description: Validate commit messages using commitlint
#         entry: commitlint --edit
#         language: node
#         pass_filenames: false
#         always_run: true

#   # Check commit messages on Travis CI (optional)
#   - repo: local
#     hooks:
#       - id: commitlint-travis
#         name: Check commit messages on Travis CI
#         description: Lint all relevant commits for a change or PR on Travis CI
#         entry: commitlint-travis
#         language: system
#         always_run: true
#         pass_filenames: false

# repos:
#   # Run ESLint for linting
#   - repo: https://github.com/pre-commit/mirrors-eslint
#     rev: v9.18.0 # Specify the version of ESLint
#     hooks:
#       - id: eslint
#         name: eslint
#         description: Lint JavaScript files using ESLint
#         entry: eslint
#         language: node
#         types: [javascript]
#         args: []
#         additional_dependencies: ['eslint@9.18.0']
#         require_serial: false
#         minimum_pre_commit_version: '2.20.0'

#   # Run Prettier for formatting
#   - repo: https://github.com/pre-commit/mirrors-prettier
#     rev: v4.0.0-alpha.8 # Specify the version of Prettier
#     hooks:
#       - id: prettier
#         name: prettier
#         description: Format files using Prettier
#         entry: prettier --write --ignore-unknown
#         language: node
#         types: [text]
#         additional_dependencies: ['prettier@4.0.0-alpha.8']
#         require_serial: false
#         minimum_pre_commit_version: '2.20.0'

#   # Run tests before committing
#   - repo: local
#     hooks:
#       - id: run-tests
#         name: Run Tests
#         description: Run all tests before committing
#         entry: npm test
#         language: system
#         pass_filenames: false
#         always_run: true

#   # Commitlint for commit message validation
#   - repo: local
#     hooks:
#       - id: commitlint
#         name: commitlint
#         description: Validate commit messages using commitlint
#         entry: npx commitlint --edit
#         language: system
#         pass_filenames: false
#         always_run: true

#     # Check commit messages on Travis CI (optional)
#   - repo: local
#     hooks:
#       - id: commitlint-travis
#         name: Check commit messages on Travis CI
#         description: Lint all relevant commits for a change or PR on Travis CI
#         entry: commitlint-travis
#         language: system
#         always_run: true
#         pass_filenames: false
